name: Build

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: ~/.esy
          key: esy-${{ matrix.os }}-${{ hashFiles('ppx/esy.lock/index.json') }}
      - run: npm install -g esy@latest
      - working-directory: ppx
        run: make
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}.exe
          path: ppx/_esy/default/build/default/.ppx/Reaml_Ppx_Bin.lib/ppx.exe
