name: Build

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Setup
        run: |
          npm install -g esy@latest
      - name: Install and Build
        run: cd ppx && make
      - name: Upload Artifacts for ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}.exe
          path: ppx/_esy/default/build/default/.ppx/Reaml_Ppx_Bin.lib/ppx.exe
