name: CI

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: ~/.esy
          key: esy-${{ matrix.os }}-${{ hashFiles('ppx/esy.lock/index.json') }}
      - run: npm install -g esy@latest
      - run: make
        working-directory: ppx
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}.exe
          path: ppx/Reaml_Ppx_Bin
