name: Test

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: ~/.esy
          key: esy-${{ matrix.os }}-${{ hashFiles('**/*.json') }}-${{ hashFiles('**/yarn.lock') }}
      - run: npm install -g esy@latest
      - working-directory: ppx
        run: make
      - run: yarn install
      - run: yarn build
      - run: yarn test
